import './globals.css'

import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import type { Metadata } from 'next'
import { Mulish } from 'next/font/google'

import { NavBar } from './_components/nav-bar'
import { Providers } from './_providers'

const mulish = Mulish({
  subsets: ['latin-ext'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ClerkProvider appearance={{ baseTheme: dark }}>
        <body
          className={`${mulish.className} dark flex w-full flex-col items-center antialiased [&::-webkit-scrollbar]:hidden`}
        >
          <Providers>
            <NavBar />
            <div className="mt-[72px] flex w-full max-w-screen-xl flex-col">{children}</div>
          </Providers>
        </body>
      </ClerkProvider>
    </html>
  )
}
